#ifndef CONSTS_H
#define CONSTS_H

#define HASH_SEED    0xB10A529F
#define HASH_NONE UINT16_MAX

#define TABLE_MAX_NAME_LENGTH 100
#define COLUMN_MAX_NAME_LENGTH 50
#define TABLE_MAX_COLUMNS 100
#define MAX_TABLES_COUNT 100

#define SECTOR_SIZE 512
#define SECTOR_PADDING 8

#endif //CONSTS_H
