/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tree.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tree.pb-c.h"
void   message__init
                     (Message         *message)
{
  static const Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   queries__init
                     (Queries         *message)
{
  static const Queries init_value = QUERIES__INIT;
  *message = init_value;
}
size_t queries__get_packed_size
                     (const Queries *message)
{
  assert(message->base.descriptor == &queries__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t queries__pack
                     (const Queries *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &queries__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t queries__pack_to_buffer
                     (const Queries *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &queries__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Queries *
       queries__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Queries *)
     protobuf_c_message_unpack (&queries__descriptor,
                                allocator, len, data);
}
void   queries__free_unpacked
                     (Queries *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &queries__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query__init
                     (Query         *message)
{
  static const Query init_value = QUERY__INIT;
  *message = init_value;
}
size_t query__get_packed_size
                     (const Query *message)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query__pack
                     (const Query *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query__pack_to_buffer
                     (const Query *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Query *
       query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Query *)
     protobuf_c_message_unpack (&query__descriptor,
                                allocator, len, data);
}
void   query__free_unpacked
                     (Query *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   exp__init
                     (Exp         *message)
{
  static const Exp init_value = EXP__INIT;
  *message = init_value;
}
size_t exp__get_packed_size
                     (const Exp *message)
{
  assert(message->base.descriptor == &exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t exp__pack
                     (const Exp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t exp__pack_to_buffer
                     (const Exp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Exp *
       exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Exp *)
     protobuf_c_message_unpack (&exp__descriptor,
                                allocator, len, data);
}
void   exp__free_unpacked
                     (Exp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set__init
                     (Set         *message)
{
  static const Set init_value = SET__INIT;
  *message = init_value;
}
size_t set__get_packed_size
                     (const Set *message)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set__pack
                     (const Set *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set__pack_to_buffer
                     (const Set *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Set *
       set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Set *)
     protobuf_c_message_unpack (&set__descriptor,
                                allocator, len, data);
}
void   set__free_unpacked
                     (Set *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_list__init
                     (SetList         *message)
{
  static const SetList init_value = SET_LIST__INIT;
  *message = init_value;
}
size_t set_list__get_packed_size
                     (const SetList *message)
{
  assert(message->base.descriptor == &set_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_list__pack
                     (const SetList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_list__pack_to_buffer
                     (const SetList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetList *
       set_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetList *)
     protobuf_c_message_unpack (&set_list__descriptor,
                                allocator, len, data);
}
void   set_list__free_unpacked
                     (SetList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_exp__init
                     (UpdateExp         *message)
{
  static const UpdateExp init_value = UPDATE_EXP__INIT;
  *message = init_value;
}
size_t update_exp__get_packed_size
                     (const UpdateExp *message)
{
  assert(message->base.descriptor == &update_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_exp__pack
                     (const UpdateExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_exp__pack_to_buffer
                     (const UpdateExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateExp *
       update_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateExp *)
     protobuf_c_message_unpack (&update_exp__descriptor,
                                allocator, len, data);
}
void   update_exp__free_unpacked
                     (UpdateExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reference__init
                     (Reference         *message)
{
  static const Reference init_value = REFERENCE__INIT;
  *message = init_value;
}
size_t reference__get_packed_size
                     (const Reference *message)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reference__pack
                     (const Reference *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reference__pack_to_buffer
                     (const Reference *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reference *
       reference__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reference *)
     protobuf_c_message_unpack (&reference__descriptor,
                                allocator, len, data);
}
void   reference__free_unpacked
                     (Reference *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reference__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reference_list__init
                     (ReferenceList         *message)
{
  static const ReferenceList init_value = REFERENCE_LIST__INIT;
  *message = init_value;
}
size_t reference_list__get_packed_size
                     (const ReferenceList *message)
{
  assert(message->base.descriptor == &reference_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reference_list__pack
                     (const ReferenceList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reference_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reference_list__pack_to_buffer
                     (const ReferenceList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reference_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReferenceList *
       reference_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReferenceList *)
     protobuf_c_message_unpack (&reference_list__descriptor,
                                allocator, len, data);
}
void   reference_list__free_unpacked
                     (ReferenceList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reference_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table__init
                     (Table         *message)
{
  static const Table init_value = TABLE__INIT;
  *message = init_value;
}
size_t table__get_packed_size
                     (const Table *message)
{
  assert(message->base.descriptor == &table__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table__pack
                     (const Table *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table__pack_to_buffer
                     (const Table *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Table *
       table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Table *)
     protobuf_c_message_unpack (&table__descriptor,
                                allocator, len, data);
}
void   table__free_unpacked
                     (Table *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   column__init
                     (Column         *message)
{
  static const Column init_value = COLUMN__INIT;
  *message = init_value;
}
size_t column__get_packed_size
                     (const Column *message)
{
  assert(message->base.descriptor == &column__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t column__pack
                     (const Column *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &column__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t column__pack_to_buffer
                     (const Column *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &column__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Column *
       column__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Column *)
     protobuf_c_message_unpack (&column__descriptor,
                                allocator, len, data);
}
void   column__free_unpacked
                     (Column *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &column__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   select_exp__init
                     (SelectExp         *message)
{
  static const SelectExp init_value = SELECT_EXP__INIT;
  *message = init_value;
}
size_t select_exp__get_packed_size
                     (const SelectExp *message)
{
  assert(message->base.descriptor == &select_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t select_exp__pack
                     (const SelectExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &select_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t select_exp__pack_to_buffer
                     (const SelectExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &select_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SelectExp *
       select_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SelectExp *)
     protobuf_c_message_unpack (&select_exp__descriptor,
                                allocator, len, data);
}
void   select_exp__free_unpacked
                     (SelectExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &select_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   where__init
                     (Where         *message)
{
  static const Where init_value = WHERE__INIT;
  *message = init_value;
}
size_t where__get_packed_size
                     (const Where *message)
{
  assert(message->base.descriptor == &where__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t where__pack
                     (const Where *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &where__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t where__pack_to_buffer
                     (const Where *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &where__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Where *
       where__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Where *)
     protobuf_c_message_unpack (&where__descriptor,
                                allocator, len, data);
}
void   where__free_unpacked
                     (Where *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &where__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delete_exp__init
                     (DeleteExp         *message)
{
  static const DeleteExp init_value = DELETE_EXP__INIT;
  *message = init_value;
}
size_t delete_exp__get_packed_size
                     (const DeleteExp *message)
{
  assert(message->base.descriptor == &delete_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_exp__pack
                     (const DeleteExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_exp__pack_to_buffer
                     (const DeleteExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteExp *
       delete_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteExp *)
     protobuf_c_message_unpack (&delete_exp__descriptor,
                                allocator, len, data);
}
void   delete_exp__free_unpacked
                     (DeleteExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delete_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_list__init
                     (FieldList         *message)
{
  static const FieldList init_value = FIELD_LIST__INIT;
  *message = init_value;
}
size_t field_list__get_packed_size
                     (const FieldList *message)
{
  assert(message->base.descriptor == &field_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_list__pack
                     (const FieldList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_list__pack_to_buffer
                     (const FieldList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldList *
       field_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldList *)
     protobuf_c_message_unpack (&field_list__descriptor,
                                allocator, len, data);
}
void   field_list__free_unpacked
                     (FieldList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field__init
                     (Field         *message)
{
  static const Field init_value = FIELD__INIT;
  *message = init_value;
}
size_t field__get_packed_size
                     (const Field *message)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field__pack
                     (const Field *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field__pack_to_buffer
                     (const Field *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Field *
       field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Field *)
     protobuf_c_message_unpack (&field__descriptor,
                                allocator, len, data);
}
void   field__free_unpacked
                     (Field *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_exp__init
                     (CreateExp         *message)
{
  static const CreateExp init_value = CREATE_EXP__INIT;
  *message = init_value;
}
size_t create_exp__get_packed_size
                     (const CreateExp *message)
{
  assert(message->base.descriptor == &create_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_exp__pack
                     (const CreateExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_exp__pack_to_buffer
                     (const CreateExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateExp *
       create_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateExp *)
     protobuf_c_message_unpack (&create_exp__descriptor,
                                allocator, len, data);
}
void   create_exp__free_unpacked
                     (CreateExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &create_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   values_list__init
                     (ValuesList         *message)
{
  static const ValuesList init_value = VALUES_LIST__INIT;
  *message = init_value;
}
size_t values_list__get_packed_size
                     (const ValuesList *message)
{
  assert(message->base.descriptor == &values_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t values_list__pack
                     (const ValuesList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &values_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t values_list__pack_to_buffer
                     (const ValuesList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &values_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ValuesList *
       values_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ValuesList *)
     protobuf_c_message_unpack (&values_list__descriptor,
                                allocator, len, data);
}
void   values_list__free_unpacked
                     (ValuesList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &values_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insert_exp__init
                     (InsertExp         *message)
{
  static const InsertExp init_value = INSERT_EXP__INIT;
  *message = init_value;
}
size_t insert_exp__get_packed_size
                     (const InsertExp *message)
{
  assert(message->base.descriptor == &insert_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insert_exp__pack
                     (const InsertExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insert_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insert_exp__pack_to_buffer
                     (const InsertExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insert_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InsertExp *
       insert_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InsertExp *)
     protobuf_c_message_unpack (&insert_exp__descriptor,
                                allocator, len, data);
}
void   insert_exp__free_unpacked
                     (InsertExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insert_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drop_exp__init
                     (DropExp         *message)
{
  static const DropExp init_value = DROP_EXP__INIT;
  *message = init_value;
}
size_t drop_exp__get_packed_size
                     (const DropExp *message)
{
  assert(message->base.descriptor == &drop_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drop_exp__pack
                     (const DropExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drop_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drop_exp__pack_to_buffer
                     (const DropExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drop_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DropExp *
       drop_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DropExp *)
     protobuf_c_message_unpack (&drop_exp__descriptor,
                                allocator, len, data);
}
void   drop_exp__free_unpacked
                     (DropExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drop_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logic_exp__init
                     (LogicExp         *message)
{
  static const LogicExp init_value = LOGIC_EXP__INIT;
  *message = init_value;
}
size_t logic_exp__get_packed_size
                     (const LogicExp *message)
{
  assert(message->base.descriptor == &logic_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logic_exp__pack
                     (const LogicExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logic_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logic_exp__pack_to_buffer
                     (const LogicExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logic_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LogicExp *
       logic_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LogicExp *)
     protobuf_c_message_unpack (&logic_exp__descriptor,
                                allocator, len, data);
}
void   logic_exp__free_unpacked
                     (LogicExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logic_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   compare_exp__init
                     (CompareExp         *message)
{
  static const CompareExp init_value = COMPARE_EXP__INIT;
  *message = init_value;
}
size_t compare_exp__get_packed_size
                     (const CompareExp *message)
{
  assert(message->base.descriptor == &compare_exp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t compare_exp__pack
                     (const CompareExp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &compare_exp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t compare_exp__pack_to_buffer
                     (const CompareExp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &compare_exp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CompareExp *
       compare_exp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CompareExp *)
     protobuf_c_message_unpack (&compare_exp__descriptor,
                                allocator, len, data);
}
void   compare_exp__free_unpacked
                     (CompareExp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &compare_exp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value__init
                     (Value         *message)
{
  static const Value init_value = VALUE__INIT;
  *message = init_value;
}
size_t value__get_packed_size
                     (const Value *message)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value__pack
                     (const Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value__pack_to_buffer
                     (const Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Value *
       value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Value *)
     protobuf_c_message_unpack (&value__descriptor,
                                allocator, len, data);
}
void   value__free_unpacked
                     (Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message__field_descriptors[2] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, content_case),
    offsetof(Message, request),
    &request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, content_case),
    offsetof(Message, response),
    &response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  0,   /* field[0] = request */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  2,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[1] =
{
  {
    "string",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  0,   /* field[0] = string */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  1,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[1] =
{
  {
    "queries",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, queries),
    &queries__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  0,   /* field[0] = queries */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  1,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor queries__field_descriptors[1] =
{
  {
    "queries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Queries, n_queries),
    offsetof(Queries, queries),
    &query__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned queries__field_indices_by_name[] = {
  0,   /* field[0] = queries */
};
static const ProtobufCIntRange queries__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor queries__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Queries",
  "Queries",
  "Queries",
  "",
  sizeof(Queries),
  1,
  queries__field_descriptors,
  queries__field_indices_by_name,
  1,  queries__number_ranges,
  (ProtobufCMessageInit) queries__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query__field_descriptors[6] =
{
  {
    "select_exp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, select_exp),
    &select_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_exp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, update_exp),
    &update_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_exp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, create_exp),
    &create_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_exp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, delete_exp),
    &delete_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insert_exp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, insert_exp),
    &insert_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_exp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Query, content_case),
    offsetof(Query, drop_exp),
    &drop_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__field_indices_by_name[] = {
  2,   /* field[2] = create_exp */
  3,   /* field[3] = delete_exp */
  5,   /* field[5] = drop_exp */
  4,   /* field[4] = insert_exp */
  0,   /* field[0] = select_exp */
  1,   /* field[1] = update_exp */
};
static const ProtobufCIntRange query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Query",
  "Query",
  "Query",
  "",
  sizeof(Query),
  6,
  query__field_descriptors,
  query__field_indices_by_name,
  1,  query__number_ranges,
  (ProtobufCMessageInit) query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor exp__field_descriptors[4] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Exp, content_case),
    offsetof(Exp, value),
    &value__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compare_exp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Exp, content_case),
    offsetof(Exp, compare_exp),
    &compare_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logic_exp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Exp, content_case),
    offsetof(Exp, logic_exp),
    &logic_exp__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reference",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Exp, content_case),
    offsetof(Exp, reference),
    &reference__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned exp__field_indices_by_name[] = {
  1,   /* field[1] = compare_exp */
  2,   /* field[2] = logic_exp */
  3,   /* field[3] = reference */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Exp",
  "Exp",
  "Exp",
  "",
  sizeof(Exp),
  4,
  exp__field_descriptors,
  exp__field_indices_by_name,
  1,  exp__number_ranges,
  (ProtobufCMessageInit) exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set__field_descriptors[2] =
{
  {
    "column",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Set, column),
    &column__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Set, value),
    &value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set__field_indices_by_name[] = {
  0,   /* field[0] = column */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Set",
  "Set",
  "Set",
  "",
  sizeof(Set),
  2,
  set__field_descriptors,
  set__field_indices_by_name,
  1,  set__number_ranges,
  (ProtobufCMessageInit) set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_list__field_descriptors[1] =
{
  {
    "set_list",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SetList, n_set_list),
    offsetof(SetList, set_list),
    &set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_list__field_indices_by_name[] = {
  0,   /* field[0] = set_list */
};
static const ProtobufCIntRange set_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetList",
  "SetList",
  "SetList",
  "",
  sizeof(SetList),
  1,
  set_list__field_descriptors,
  set_list__field_indices_by_name,
  1,  set_list__number_ranges,
  (ProtobufCMessageInit) set_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor update_exp__field_descriptors[3] =
{
  {
    "set_list",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateExp, set_list),
    &set_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "where",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateExp, where),
    &where__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_exp__field_indices_by_name[] = {
  0,   /* field[0] = set_list */
  1,   /* field[1] = table */
  2,   /* field[2] = where */
};
static const ProtobufCIntRange update_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor update_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateExp",
  "UpdateExp",
  "UpdateExp",
  "",
  sizeof(UpdateExp),
  3,
  update_exp__field_descriptors,
  update_exp__field_indices_by_name,
  1,  update_exp__number_ranges,
  (ProtobufCMessageInit) update_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reference__field_descriptors[2] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Reference, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Reference, column),
    &column__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reference__field_indices_by_name[] = {
  1,   /* field[1] = column */
  0,   /* field[0] = table */
};
static const ProtobufCIntRange reference__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reference__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reference",
  "Reference",
  "Reference",
  "",
  sizeof(Reference),
  2,
  reference__field_descriptors,
  reference__field_indices_by_name,
  1,  reference__number_ranges,
  (ProtobufCMessageInit) reference__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reference_list__field_descriptors[1] =
{
  {
    "reference",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ReferenceList, n_reference),
    offsetof(ReferenceList, reference),
    &reference__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reference_list__field_indices_by_name[] = {
  0,   /* field[0] = reference */
};
static const ProtobufCIntRange reference_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor reference_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReferenceList",
  "ReferenceList",
  "ReferenceList",
  "",
  sizeof(ReferenceList),
  1,
  reference_list__field_descriptors,
  reference_list__field_indices_by_name,
  1,  reference_list__number_ranges,
  (ProtobufCMessageInit) reference_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table__field_descriptors[1] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Table, table),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table__field_indices_by_name[] = {
  0,   /* field[0] = table */
};
static const ProtobufCIntRange table__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor table__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Table",
  "Table",
  "Table",
  "",
  sizeof(Table),
  1,
  table__field_descriptors,
  table__field_indices_by_name,
  1,  table__number_ranges,
  (ProtobufCMessageInit) table__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor column__field_descriptors[1] =
{
  {
    "column",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Column, column),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned column__field_indices_by_name[] = {
  0,   /* field[0] = column */
};
static const ProtobufCIntRange column__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor column__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Column",
  "Column",
  "Column",
  "",
  sizeof(Column),
  1,
  column__field_descriptors,
  column__field_indices_by_name,
  1,  column__number_ranges,
  (ProtobufCMessageInit) column__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor select_exp__field_descriptors[3] =
{
  {
    "reference_list",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectExp, reference_list),
    &reference_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "where",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectExp, where),
    &where__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned select_exp__field_indices_by_name[] = {
  0,   /* field[0] = reference_list */
  1,   /* field[1] = table */
  2,   /* field[2] = where */
};
static const ProtobufCIntRange select_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor select_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SelectExp",
  "SelectExp",
  "SelectExp",
  "",
  sizeof(SelectExp),
  3,
  select_exp__field_descriptors,
  select_exp__field_indices_by_name,
  1,  select_exp__number_ranges,
  (ProtobufCMessageInit) select_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor where__field_descriptors[1] =
{
  {
    "exp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Where, exp),
    &exp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned where__field_indices_by_name[] = {
  0,   /* field[0] = exp */
};
static const ProtobufCIntRange where__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor where__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Where",
  "Where",
  "Where",
  "",
  sizeof(Where),
  1,
  where__field_descriptors,
  where__field_indices_by_name,
  1,  where__number_ranges,
  (ProtobufCMessageInit) where__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delete_exp__field_descriptors[2] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeleteExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "where",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DeleteExp, where),
    &where__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_exp__field_indices_by_name[] = {
  0,   /* field[0] = table */
  1,   /* field[1] = where */
};
static const ProtobufCIntRange delete_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor delete_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteExp",
  "DeleteExp",
  "DeleteExp",
  "",
  sizeof(DeleteExp),
  2,
  delete_exp__field_descriptors,
  delete_exp__field_indices_by_name,
  1,  delete_exp__number_ranges,
  (ProtobufCMessageInit) delete_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_list__field_descriptors[1] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FieldList, n_field),
    offsetof(FieldList, field),
    &field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_list__field_indices_by_name[] = {
  0,   /* field[0] = field */
};
static const ProtobufCIntRange field_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor field_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldList",
  "FieldList",
  "FieldList",
  "",
  sizeof(FieldList),
  1,
  field_list__field_descriptors,
  field_list__field_indices_by_name,
  1,  field_list__number_ranges,
  (ProtobufCMessageInit) field_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field__field_descriptors[2] =
{
  {
    "column",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Field, column),
    &column__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Field, field_type),
    &field_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field__field_indices_by_name[] = {
  0,   /* field[0] = column */
  1,   /* field[1] = field_type */
};
static const ProtobufCIntRange field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Field",
  "Field",
  "Field",
  "",
  sizeof(Field),
  2,
  field__field_descriptors,
  field__field_indices_by_name,
  1,  field__number_ranges,
  (ProtobufCMessageInit) field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_exp__field_descriptors[2] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CreateExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_list",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CreateExp, field_list),
    &field_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_exp__field_indices_by_name[] = {
  1,   /* field[1] = field_list */
  0,   /* field[0] = table */
};
static const ProtobufCIntRange create_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor create_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateExp",
  "CreateExp",
  "CreateExp",
  "",
  sizeof(CreateExp),
  2,
  create_exp__field_descriptors,
  create_exp__field_indices_by_name,
  1,  create_exp__number_ranges,
  (ProtobufCMessageInit) create_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor values_list__field_descriptors[1] =
{
  {
    "values_list",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ValuesList, n_values_list),
    offsetof(ValuesList, values_list),
    &value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned values_list__field_indices_by_name[] = {
  0,   /* field[0] = values_list */
};
static const ProtobufCIntRange values_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor values_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ValuesList",
  "ValuesList",
  "ValuesList",
  "",
  sizeof(ValuesList),
  1,
  values_list__field_descriptors,
  values_list__field_indices_by_name,
  1,  values_list__number_ranges,
  (ProtobufCMessageInit) values_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insert_exp__field_descriptors[2] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InsertExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values_list",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InsertExp, values_list),
    &values_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insert_exp__field_indices_by_name[] = {
  0,   /* field[0] = table */
  1,   /* field[1] = values_list */
};
static const ProtobufCIntRange insert_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insert_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InsertExp",
  "InsertExp",
  "InsertExp",
  "",
  sizeof(InsertExp),
  2,
  insert_exp__field_descriptors,
  insert_exp__field_indices_by_name,
  1,  insert_exp__number_ranges,
  (ProtobufCMessageInit) insert_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drop_exp__field_descriptors[1] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DropExp, table),
    &table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drop_exp__field_indices_by_name[] = {
  0,   /* field[0] = table */
};
static const ProtobufCIntRange drop_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor drop_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DropExp",
  "DropExp",
  "DropExp",
  "",
  sizeof(DropExp),
  1,
  drop_exp__field_descriptors,
  drop_exp__field_indices_by_name,
  1,  drop_exp__number_ranges,
  (ProtobufCMessageInit) drop_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logic_exp__field_descriptors[3] =
{
  {
    "logic",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LogicExp, logic),
    &logic_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LogicExp, left),
    &exp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LogicExp, right),
    &exp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logic_exp__field_indices_by_name[] = {
  1,   /* field[1] = left */
  0,   /* field[0] = logic */
  2,   /* field[2] = right */
};
static const ProtobufCIntRange logic_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor logic_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LogicExp",
  "LogicExp",
  "LogicExp",
  "",
  sizeof(LogicExp),
  3,
  logic_exp__field_descriptors,
  logic_exp__field_indices_by_name,
  1,  logic_exp__number_ranges,
  (ProtobufCMessageInit) logic_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor compare_exp__field_descriptors[3] =
{
  {
    "compare",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CompareExp, compare),
    &compare_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CompareExp, left),
    &exp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CompareExp, right),
    &exp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned compare_exp__field_indices_by_name[] = {
  0,   /* field[0] = compare */
  1,   /* field[1] = left */
  2,   /* field[2] = right */
};
static const ProtobufCIntRange compare_exp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor compare_exp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CompareExp",
  "CompareExp",
  "CompareExp",
  "",
  sizeof(CompareExp),
  3,
  compare_exp__field_descriptors,
  compare_exp__field_indices_by_name,
  1,  compare_exp__number_ranges,
  (ProtobufCMessageInit) compare_exp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value__field_descriptors[4] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Value, content_case),
    offsetof(Value, int_),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Value, content_case),
    offsetof(Value, float_),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Value, content_case),
    offsetof(Value, string),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Value, content_case),
    offsetof(Value, bool_),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value__field_indices_by_name[] = {
  3,   /* field[3] = bool */
  1,   /* field[1] = float */
  0,   /* field[0] = int */
  2,   /* field[2] = string */
};
static const ProtobufCIntRange value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Value",
  "Value",
  "Value",
  "",
  sizeof(Value),
  4,
  value__field_descriptors,
  value__field_indices_by_name,
  1,  value__number_ranges,
  (ProtobufCMessageInit) value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue compare_type__enum_values_by_number[6] =
{
  { "GEQ", "COMPARE_TYPE__GEQ", 0 },
  { "LEQ", "COMPARE_TYPE__LEQ", 1 },
  { "LESS", "COMPARE_TYPE__LESS", 2 },
  { "GREATER", "COMPARE_TYPE__GREATER", 3 },
  { "EQ", "COMPARE_TYPE__EQ", 4 },
  { "NEQ", "COMPARE_TYPE__NEQ", 5 },
};
static const ProtobufCIntRange compare_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex compare_type__enum_values_by_name[6] =
{
  { "EQ", 4 },
  { "GEQ", 0 },
  { "GREATER", 3 },
  { "LEQ", 1 },
  { "LESS", 2 },
  { "NEQ", 5 },
};
const ProtobufCEnumDescriptor compare_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CompareType",
  "CompareType",
  "CompareType",
  "",
  6,
  compare_type__enum_values_by_number,
  6,
  compare_type__enum_values_by_name,
  1,
  compare_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue field_type__enum_values_by_number[4] =
{
  { "INT_FIELD", "FIELD_TYPE__INT_FIELD", 0 },
  { "FLOAT_FIELD", "FIELD_TYPE__FLOAT_FIELD", 1 },
  { "STRING_FIELD", "FIELD_TYPE__STRING_FIELD", 2 },
  { "BOOL_FIELD", "FIELD_TYPE__BOOL_FIELD", 3 },
};
static const ProtobufCIntRange field_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex field_type__enum_values_by_name[4] =
{
  { "BOOL_FIELD", 3 },
  { "FLOAT_FIELD", 1 },
  { "INT_FIELD", 0 },
  { "STRING_FIELD", 2 },
};
const ProtobufCEnumDescriptor field_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FieldType",
  "FieldType",
  "FieldType",
  "",
  4,
  field_type__enum_values_by_number,
  4,
  field_type__enum_values_by_name,
  1,
  field_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue logic_type__enum_values_by_number[3] =
{
  { "OR", "LOGIC_TYPE__OR", 0 },
  { "AND", "LOGIC_TYPE__AND", 1 },
  { "NOT", "LOGIC_TYPE__NOT", 2 },
};
static const ProtobufCIntRange logic_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex logic_type__enum_values_by_name[3] =
{
  { "AND", 1 },
  { "NOT", 2 },
  { "OR", 0 },
};
const ProtobufCEnumDescriptor logic_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LogicType",
  "LogicType",
  "LogicType",
  "",
  3,
  logic_type__enum_values_by_number,
  3,
  logic_type__enum_values_by_name,
  1,
  logic_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
